name: SimpleCommands
main: xyz.acrylicstyle.simplecommands.SimpleCommands
version: 1.0-SNAPSHOT
api-version: "1.15"
commands:
  suicide:
    description: "Kills yourself. Why would you do that?"
    permission: simplecommands.suicide
  pingall:
    description: "Shows everyone's ping"
    permission: simplecommands.pingall
  teleportworld:
    aliases: ["tpworld", "tpw"]
    permission: simplecommands.teleportworld
  textures:
    description: ""
    aliases: ["texture", "/texture", "resource", "resourcepack"]
  crash:
    description: ""